### ISSUE TITLE
Can I add in my website /docs page

### ISSUE THREAD

**Issue by peteryang1756** [fuma-nama/next-docs#107]
Hello, can I install next-docs into /docs on my original website?, if so how to do it?

**Comment by fuma-nama** [comment]
For a Next.js project using App Router, You can follow the [manual setup guide](https://next-docs-zeta.vercel.app/docs/ui). Install dependencies and copy & paste required files manually.

**Comment by sxadxsx** [comment]
@fuma-nama how to fix this question?
`

Error: Catch-all must be the last part of the URL.
--
10:18:55.239 | at UrlNode._insert (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:54:19)
10:18:55.239 | at UrlNode._insert (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:136:40)
10:18:55.239 | at UrlNode._insert (/vercel/path0/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:136:40)

`

**Comment by fuma-nama** [comment]
Please open another issue, and provide steps to reproduce your problem.
