### ISSUE TITLE
CSS stylesheet not loading properly

### ISSUE THREAD

**Issue by peteryang1756** [fuma-nama/next-docs#108]
How to fix this question?
![F7871F4D-3BE4-4982-B084-311EF0EFB1A0](https://github.com/fuma-nama/next-docs/assets/92738287/c7fd22f0-d706-4a7f-ac09-398d7d6921c1)

**Comment by fuma-nama** [comment]
Have you imported the CSS stylesheet in root layout?
```diff
+ import 'next-docs-ui/style.css'
```
