### ISSUE TITLE
Please either define a filePathPattern for the given document type definition or provide a valid value for the type field (i.e. the field "type" needs to be one of the following document type names: Docs, Meta).

### ISSUE THREAD

**Issue by sxadxsx** [fuma-nama/next-docs#110]
`Please either define a filePathPattern for the given document type definition or provide a valid value for the type field (i.e. the field "type" needs to be one of the following document type names: Docs, Meta).`
What worng?

**Comment by fuma-nama** [comment]
Please provide more information to your issue

**Comment by sxadxsx** [comment]
@fuma-nama I try to write index.mdx and get this error

**Comment by fuma-nama** [comment]
Where did you created the file? Can you also provide your Contentlayer configuration, as well as a reproducible repository will be appreciated.

**Comment by sxadxsx** [comment]
@fuma-nama I add it in content/docs /index.mdx
And this is my contentlayer.config.ts
`import { makeSource } from 'contentlayer/source-files'
import { defaultConfig } from 'next-docs-zeta/contentlayer/configuration'

export default makeSource(defaultConfig)`

**Comment by fuma-nama** [comment]
I can't reproduce your error, it works perfectly on 3.0.0 on Next.js 13.5.6. Can you provide a minimal reproducible repository? 
You may take a look at our [official template](https://github.com/fuma-nama/next-docs-ui-template) to check if you've made any mistakes in your code.

Try it on CodeSandbox: https://githubbox.com/SonMooSans/next-docs-ui-template

**Comment by sxadxsx** [comment]
@fuma-nama this is my repository url:https://github.com/sxadxsx/Ssport-website/tree/main/app/docs
