### ISSUE TITLE
icon page

### ISSUE THREAD

**Issue by CMAULTOP** [fuma-nama/next-docs#144]
**Is your feature request related to a problem? Please describe.**
Adding icons next to the page name. So implemented in mintlife and looks very nice.
here's how it's done in mintlify:
![image](https://github.com/fuma-nama/next-docs/assets/55154964/1307b133-adab-460b-b3bf-706656f1ec1d)
here's what it should look like in next docs:
![image](https://github.com/fuma-nama/next-docs/assets/55154964/60e6c501-529b-4242-bdfd-c453f9213e5e)

**Describe the solution you'd like**
Just push the svg icon into the <a> side menu.
Here's how it should probably look like:
`<a class="nd-flex nd-flex-row nd-items-center nd-gap-2 nd-font-medium nd-px-2 nd-py-1.5 nd-rounded-md [&amp;_svg]:nd-w-4 [&amp;_svg]:nd-h-4 nd-text-primary nd-bg-primary/10" href="/docs/headless">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-github"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"></path><path d="M9 18c-4.51 2-5-2-7-2"></path></svg>
Quick Start</a>`

Well, the file just has a new value icon='{icon}', I do not know svg or through some libraries

**Comment by CMAULTOP** [comment]
I rummaged through the code and found something similar to adding an icon, but I didn't find a word about it in the documentation

**Comment by fuma-nama** [comment]
Read: https://next-docs-zeta.vercel.app/docs/headless/contentlayer/config#adding-icons

**Comment by fuma-nama** [comment]
Now documented at https://next-docs-zeta.vercel.app/docs/headless/utils/build-page-tree#icons
