### ISSUE TITLE
Creating a project via the CLI does not work

### ISSUE THREAD

**Issue by CMAULTOP** [fuma-nama/next-docs#145]
![image](https://github.com/fuma-nama/next-docs/assets/55154964/eb2f36db-1839-4747-8b99-b745cca6e626)

**Comment by fuma-nama** [comment]
What is your node.js version?

**Comment by CMAULTOP** [comment]
v20.8.0

**Comment by fuma-nama** [comment]
Got it, maybe transpiling it into commonjs format will have a better compatibility. Since I can’t reproduce the problem on my development machine, I can’t guarantee the fix works

**Comment by CMAULTOP** [comment]
In general, I also tried not on my own, but on github codespaces

**Comment by fuma-nama** [comment]
The latest version of [create-next-docs-app@1.7.2](https://github.com/fuma-nama/next-docs/releases/tag/create-next-docs-app%401.7.2) should have fixed the error, please open again if the issue retains.
