### ISSUE TITLE
why my navbar search button not working?

### ISSUE THREAD

**Issue by sxadxsx** [fuma-nama/next-docs#162]
why my navbar search button not working?
url:https://ssport-website-git-fork-sxadxsx-main-ssangyongsports.vercel.app/docs
github:https://github.com/sxadxsx/Ssport-website-docs/tree/main/app

**Comment by fuma-nama** [comment]
You missed the root provider in your layout, please follow the setup guide or bootstrap a new app with `create-next-docs-app`
