### ISSUE TITLE
Changing SearchToggle position

### ISSUE THREAD

**Issue by pomber** [fuma-nama/next-docs#222]
Hi, I'm thinking of using this project for the new [Code Hike](https://codehike.org/) website.  

I was wondering if it will be possible to move the SearchToggle from the navbar to other places. I like how [tailwindcss](https://tailwindcss.com/) does it. 

SearchToggle in page body:
![image](https://github.com/fuma-nama/next-docs/assets/1911623/cf9fe424-9b3d-4537-acf6-68f6bd72fbce)

SearchToggle in the sidebar:
![image](https://github.com/fuma-nama/next-docs/assets/1911623/4dce368e-6235-4bc2-b8b2-68aa0b6fd5b3)

**Comment by fuma-nama** [comment]
That is not possible for now, the search toggle component itself is not exported and is only intended for internal use. 
I can add this as a new feature in the next major.
