### ISSUE TITLE
[UI]: Nav component missing transparent prop

### ISSUE THREAD

**Issue by jaaneh** [fuma-nama/next-docs#65]
Hey there.

Loving these libraries, been a blast to use so far.

I'm importing the Nav component from `next-docs-ui/components` and want to apply the `transparent` prop, but it doesn't exist and isn't available to me. I see it's used in your examples and the docs also.

```ts
Property 'transparent' does not exist on type 'IntrinsicAttributes & NavProps'.
```
```json
"next-docs-ui": "^2.0.3",
"next-docs-zeta": "^2.0.3",
```

Thank you!

**Comment by fuma-nama** [comment]
It is only available on 2.1.0, you can check the package version on sidebar.

![image](https://github.com/fuma-nama/next-docs/assets/76240755/edff3a68-2ba8-4415-ab2b-6aed5cd21768)

**Comment by jaaneh** [comment]
> It is only available on 2.1.0, you can check the package version on sidebar.

2.1.0 is not available on npm.

**Comment by fuma-nama** [comment]
Seems like changeset has encountered some bugs, I've just manually released the package on npm.

**Comment by jaaneh** [comment]
Works fine! Thank you!
